server:
  port: 8901

dubbo:
  application:
    name: dubbo-demo-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: multicast://224.5.6.7:1234
    id: registry